
#!/bin/bash

#my variables for commands to get system info, which i will use in the tempelate

myusername=($USER)
today=$(date)
myhostname=$(hostname)
OS=$(source /etc/os-release && echo $PRETTY_NAME)
starttime=$(uptime | awk '{print $3,$4}' | sed 's/,//')
mycpu=$(lscpu | grep "Model name")
pcspeed=$(sudo dmidecode -t processor | grep Speed)
ramspecifications=$(free -h)
noofdisks=$(lsblk)
videocard=$(sudo lshw -C video)
myfqdn=$(hostname --fqdn)
myaddress=$(hostname -I)
mygateway=$(ip route | grep default | awk '{print $3}')
dns=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')
nameofinterface=$(ip -o link show | awk -F': ' '{print $2}')
noOfUsers=$(w)
myDisk=$(df)
pCount=$(ps -e | wc -l)
myLoad=$(uptime | grep 'load average')
allocatedMemory=$(free -h)
lNetPorts=$(ss -tuln)
rules=$(sudo ufw status)
ip=$(ip addr)
cat <<EOF

#here is my system information REPORT in the form of script

System Report generated by $USER, $today

#firstly. here is some information about system


System information
-----------------
Hostname =  $myhostname
Operating System =  $OS
Uptime = $starttime


#here are the commands to get information about hardware

Hardware Information
----------------------
cpu = $mycpu
Speed =$pcspeed
Ram =  $ramspecifications
Disk(s) =  $noofdisks
Video =  $videocard

#some information about network of my machine 

Network Information
---------------------
FQDN =  $myfqdn
Host Address =  $myaddress
Gateway IP =  $mygateway
DNS Server = $dns
InterfaceName = $nameofinterface

IP Address = $ip

#lastly, here is some system status information of current situations

System Status
--------------
Users Logged In =  $noOfUsers
Disk Space =  $myDisk
Process Count =  $pCount
Load Averages =  $myLoad
Memory Allocation =  $allocatedMemory
Listening Network Ports =  $lNetPorts
UFW Rules = $rules

#That's my report. thanks
EOF
